import = ["~/.config/alacritty/themes/gruvbox_material.toml"]

[font]
size = 14

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[mouse]
hide_when_typing = true

[window.padding]
x = 8
y = 8
