#!/bin/sh
# ██╗  ██╗██╗███╗   ██╗██╗████████╗██████╗  ██████╗
# ╚██╗██╔╝██║████╗  ██║██║╚══██╔══╝██╔══██╗██╔════╝
#  ╚███╔╝ ██║██╔██╗ ██║██║   ██║   ██████╔╝██║
#  ██╔██╗ ██║██║╚██╗██║██║   ██║   ██╔══██╗██║
# ██╔╝ ██╗██║██║ ╚████║██║   ██║   ██║  ██║╚██████╗
# ╚═╝  ╚═╝╚═╝╚═╝  ╚═══╝╚═╝   ╚═╝   ╚═╝  ╚═╝ ╚═════╝


setxkbmap -layout pt &
xrdb ~/.Xresources &
xsetroot -cursor_name left_ptr &
xset -b &
redshift &
dunst &
compton --config ~/.compton.conf &
urxvtd -q -o -f &
mpd &
mpdscribble &

nitrogen --restore &
exec i3
